### ISSUE TITLE
`big_ls_experiment` Pipeline Timeout and Excessive Memory Usage on Local and CloudRun Deployments

### ISSUE THREAD

**Issue by chenxu2394** [latticesurgery-com/liblsqecc#123]
# Description:
Instructed by @alexandrupaler, when running the big_ls_experiment task using the pipeline wrapper with certain combination of `instructions` and `layout`, the process times out after 300 seconds and exhibits increasing memory usage from 2GB to 7GB. This issue occurs both locally and is expected to fail on Google Cloud Run due to memory constraints.

# Steps to Reproduce:

## 1. Clone the Wrapper Repository:

```bash
git clone https://github.com/chenxu2394/ls-gcp.git
cd ls-gcp
```

## 2. Build the Docker Image Locally:

```bash
docker build -t ls_gunicorn_local .
```

## 3. Run the Docker Container:

```bash
docker run -p 8080:8080 -e USE_GCS=False ls_gunicorn_local
```

## 4. Send a POST Request:

```bash
curl -X POST \
  -F "instructions=@$(pwd)/minimal_layout_inst.txt" \
  -F "layout=@$(pwd)/minimal_layout.txt" \
  http://localhost:8080/process
```
where, `minimal_layout_inst.txt` is

```bash
DeclareLogicalQubitPatches 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21
Init 1000 |+>
MultiBodyMeasure 4:Z,1000:Z
RotateSingleCellPatch 7
MultiBodyMeasure 7:X,1000:X
RotateSingleCellPatch 7
MeasureSinglePatch 1000 Z
```

And `minimal_layout.txt` is:

```bash
QrQQrQ
QrQQrQ
QrQQrQ
QrQQrQ
QrQQrQ
QrAArQ
rrrrrr
rrrrrr
111111
111111
111111
111111
```

**Expected Behavior**: The service should process the input files and return a JSON response containing the output without exceeding the timeout limit or memory constraints.

**Actual Behavior**: The process times out after 300 seconds with the following error:

```python
2024-11-16 04:31:18 ERROR:root:Exception occurred during processing
2024-11-16 04:31:18 Traceback (most recent call last):
2024-11-16 04:31:18   File "/liblsqecc/build/server.py", line 47, in process
2024-11-16 04:31:18     process = subprocess.run(
2024-11-16 04:31:18   File "/usr/local/lib/python3.8/subprocess.py", line 495, in run
2024-11-16 04:31:18     stdout, stderr = process.communicate(input, timeout=timeout)
2024-11-16 04:31:18   File "/usr/local/lib/python3.8/subprocess.py", line 1028, in communicate
2024-11-16 04:31:18     stdout, stderr = self._communicate(input, endtime, timeout)
2024-11-16 04:31:18   File "/usr/local/lib/python3.8/subprocess.py", line 1885, in _communicate
2024-11-16 04:31:18     self._check_timeout(endtime, orig_timeout, stdout, stderr)
2024-11-16 04:31:18   File "/usr/local/lib/python3.8/subprocess.py", line 1072, in _check_timeout
2024-11-16 04:31:18     raise TimeoutExpired(
2024-11-16 04:31:18 subprocess.TimeoutExpired: Command '['./lsqecc_slicer', '-i', './instructions.txt', '-l', './layout.txt', '-o', './output/minimal_layout_inst_minimal_layout.json']' timed out after 300 seconds
2024-11-16 04:31:18 172.17.0.1 - - [16/Nov/2024:02:31:18 +0000] "POST /process HTTP/1.1" 400 196 "-" "curl/8.7.1"
```

Additionally, memory usage increases from 2GB to 7GB during the processing time, exceeding the Google Cloud Run memory limit of 4GiB.

**Environment:**

- Operating System: [MacOS Sequoia 15.1]
- Docker Version: [Docker version 27.3.1, build ce12230]
- Python Version: 3.8

**Additional Context:**

- Pipeline Implementation: The pipeline is designed to wrap around `liblsqecc` and facilitate deployment on Google Cloud Run. Detailed implementation can be found in my repository: [chenxu2394/ls-gcp](https://github.com/chenxu2394/ls-gcp).
- Task Name: `big_ls_experiment`

**Comment by tylerrleblond** [comment]
Hello Chen,

This test runs locally on my laptop if I modify the instruction list to the following: 
`DeclareLogicalQubitPatches 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21
Init 1000 |+>
RotateSingleCellPatch 4
MultiBodyMeasure 4:Z,1000:Z
RotateSingleCellPatch 4
MultiBodyMeasure 7:X,1000:X
MeasureSinglePatch 1000 Z`

By default, Z-boundaries are the north and south boundaries of a patch, while X boundaries are the east and west. Thus, without rotating patch 4 before the first MultiBodyMeasure instruction (which targets its Z operator), the compiler will continually not be able to find a route. Currently, the compiler will automatically insert these rotations only for the default (Litinski's compact) layout.

**Comment by chenxu2394** [comment]
> Hello Chen,
> 
> This test runs locally on my laptop if I modify the instruction list to the following: `DeclareLogicalQubitPatches 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21 Init 1000 |+> RotateSingleCellPatch 4 MultiBodyMeasure 4:Z,1000:Z RotateSingleCellPatch 4 MultiBodyMeasure 7:X,1000:X MeasureSinglePatch 1000 Z `
> 
> By default, Z-boundaries are the north and south boundaries of a patch, while X boundaries are the east and west. Thus, without rotating patch 4 before the first MultiBodyMeasure instruction (which targets its Z operator), the compiler will continually not be able to find a route. Currently, the compiler will automatically insert these rotations only for the default (Litinski's compact) layout.

Hello Tyler, thanks for your reply. Your suggested modification works!

Just to clarify, the problematic instruction I encountered actually originates from your repository at `./examples/minimal_layout.lsi`, not something I fabricated. I assumed it should be paired with `./examples/minimal_layout.txt`. Upon compiling and running the executable directly without the wrapper, I observed infinite output:


https://github.com/user-attachments/assets/d609bd65-8b1f-48a4-a6f6-ae00ae9a5e73

**Comment by tylerrleblond** [comment]
Hi Chen, thanks for pointing this out. We did not update those examples to suit the new convention. I will look into doing so in order to eliminate future confusion.

Best,
Tyler

**Comment by chenxu2394** [comment]
Hi Tyler, since you are still familiar to the `big_ls_experiment`, could you please give some hint on what was happening below? When I send a simple request to my Flask wrapper running in Docker on my local machine, the server logs an error. Strangely, the error message appears to be empty, and the client side does not receive any indication of the error. Could you please help me understand what might be causing this issue? Any insights would be greatly appreciated!

 
![Screenshot 2024-11-19 at 23 30 19](https://github.com/user-attachments/assets/d25631ef-c530-49c7-87bc-277689b4b571)

Just in case
The `instructions.txt` is
```bash
DeclareLogicalQubitPatches 0
Init 999 |+>
MeasureSinglePatch 999 Z
Init 1000 |+>
MeasureSinglePatch 1000 Z
Init 1001 |+>
MultiBodyMeasure 0:Z,1001:X
```
And the `layout.txt` is
```bash
rrrr
rQAr
rrrr
```

**Comment by tylerrleblond** [comment]
Hi Chen, 

This might be due to the way that the LSC uses error handling to route instructions. As it stands, in all of the pipelines (streamed, dag, and wave), in the case that an encountered instruction cannot be routed, the instruction handling function within the LSC will return a pointer to a std::runtime_error object that is used to implement logic within the function that called it, e.g. whether or not to advance to the next slice. If this is the reason for what you're seeing, there is no problem at all and the LSC is operating as designed.

Separately, I find it odd that it compiled the instructions you provided onto a single slice. Can you share what command line options you used in this run?

Best,
Tyler

**Comment by chenxu2394** [comment]
> Hi Chen,
> 
> This might be due to the way that the LSC uses error handling to route instructions. As it stands, in all of the pipelines (streamed, dag, and wave), in the case that an encountered instruction cannot be routed, the instruction handling function within the LSC will return a pointer to a std::runtime_error object that is used to implement logic within the function that called it, e.g. whether or not to advance to the next slice. If this is the reason for what you're seeing, there is no problem at all and the LSC is operating as designed.
> 
> Separately, I find it odd that it compiled the instructions you provided onto a single slice. Can you share what command line options you used in this run?
> 
> Best, Tyler

Hi Tyler, thanks for your reply. And this was the command line I used:
```
cxu@MacBook-Pro-95 build 
% ./lsqecc_slicer -i ../examples/difficult_routing/instructions.lli -l ../examples/difficult_routing/layout.txt --noslices
LS Instructions read  6
Slices 1
Made patch computation. Took 0.000309417s.
```
